name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
  linux_x86_64:
    runs-on: ubuntu-latest
    name: Linux x86_64
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test
